# Étape 1 : Construction
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./

# Installer toutes les dépendances pour la construction
RUN npm install --include=dev

COPY . .

# Construire l'application
RUN npm run build

# Étape 2 : Exécution en production
FROM node:18

WORKDIR /app

# Copier uniquement les fichiers nécessaires depuis l'étape de construction
COPY --from=builder /app/.output ./.output
COPY --from=builder /app/package*.json ./

# Installer uniquement les dépendances de production
RUN npm install --only=production

EXPOSE 3000

# Démarrer l'application
CMD ["node", ".output/server/index.mjs"]
